name: Deploy

# Controls when the action will run. Triggers the workflow on push
# events but only for the main branch
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # set up node v12 for use commands (npm install)
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # install yarn globally
      - run: npm install -g yarn
      # install dependencies
      - run: yarn install --frozen-lockfile
      # use build script coming from  package.json: next build && next export
      - run: yarn build
      # use aws job configure-aws-credentials: https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      - uses: aws-actions/configure-aws-credentials@v1
        # configuration for aws-actions
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # Copy files to the production website with the AWS CLI
      - name: Copy files to the production website with the AWS CLIs
        # change with your bucket name !!
        run: aws s3 sync ./out s3://my-awesome-nextjs-app
